background {
    monitor =
    color = rgba(17, 17, 27, 1.0)
    blur_passes = 2
}

label {
    monitor =
    text = $TIME
    color = rgba(205, 214, 244, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font Mono
    position = 0, 200
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    outer_color = rgba(203, 166, 247, 1.0)
    inner_color = rgba(30, 30, 46, 0.8)
    font_color = rgba(205, 214, 244, 1.0)
    placeholder_text = Enter Password
    position = 0, -100
    halign = center
    valign = center
}
