env = AQ_NO_KMS_REQUIREMENT,1

monitor=Virtual-1,1280x800@60,0x0,1

misc {
 allow_session_lock_restore = true
 disable_hyprland_logo = true
 disable_splash_rendering = true
 splash_font_family =
}

debug {
  disable_logs = false
}

exec-once=waybar

input {
  kb_layout=us
}

general {
  gaps_in=5
  gaps_out=10
  border_size=1
  col.active_border = rgba(cba6f7ff)
}

exec-once = hyprpaper
exec-once = sleep 2 && hyprctl hyprpaper wallpaper "Virtual-1,/home/ee/wallpapers/amethyst/amethyst1.jpg"
exec-once = pkill prlcp || true

bind = SUPER, Return, exec, kitty
bind = SUPERSHIFT, Q, killactive
bind = SUPER, M, exit
bind = SUPER, h, movefocus,l
bind = SUPER, l, movefocus,r
bind = SUPER, k, movefocus,u
bind = SUPER, j, movefocus,d
bind = SUPER, b, exec,firefox
bind = SUPER, F, fullscreen

# Switch to workspace
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

# Move focused window to workspace
bind = SUPERSHIFT, 1, movetoworkspace, 1
bind = SUPERSHIFT, 2, movetoworkspace, 2
bind = SUPERSHIFT, 3, movetoworkspace, 3
bind = SUPERSHIFT, 4, movetoworkspace, 4
bind = SUPERSHIFT, 5, movetoworkspace, 5


# Toggle to last workspace
bind = SUPER, P, workspace, previous

bind = SUPERSHIFT, V, exec, hyprctl dispatch togglefloating && hyprtcl dispatch resizeactive exact 900 600 && hyprctl dispatch centerwindow

bind = SUPERSHIFT, R, resizeactive, 50 50
