onboarding = false

[theme]
name = "tokyo-night"
auto_switch = false

[keys]
prefix = "ctrl+s"

[[keys.command]]
key = "prefix+minus"
type = "plugin_action"
command = "custom.pane-namer.split-down-named"

[[keys.command]]
key = "prefix+\\"
type = "plugin_action"
command = "custom.pane-namer.split-right-named"

[ui]
accent = "#af87ff"
window_title = "{workspace}"
