#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Which Mail
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 📫

# Documentation:
# @raycast.description Open Mail or Outlook

if [[ "$(hostname)" == "MB-EKATHURIA.magmutual.com" ]]; then
  open -a "Microsoft Outlook"
else
  open -a "Mail"
fi
